# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    push:
      branches: [ "main" ]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    web-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Get latest code
          uses: actions/checkout@v4
    
        - name: Push files
          uses: SamKirkland/FTP-Deploy-Action@v4.3.5
          with:
            server: ${{ secrets.ftp_server }}
            server-dir: "./htdocs/"
            username: ${{ secrets.ftp_user }}
            password: ${{ secrets.ftp_password }}
